CREATE TABLE IF NOT EXISTS connectors (
    id SERIAL PRIMARY KEY,
    station_id INTEGER REFERENCES stations(id) ON DELETE CASCADE,
    connector_type VARCHAR(20) NOT NULL,
    power_kw DECIMAL(5,1) NOT NULL,
    status VARCHAR(30) DEFAULT 'AVAILABLE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);